- packages/docs/fluent-editor/.vitepress/theme/vars.css
- packages/docs/fluent-editor/docs/basic-usage.md
- packages/docs/fluent-editor/docs/code-block-highlight.md
- packages/docs/fluent-editor/docs/custom-toolbar.md
- packages/docs/fluent-editor/docs/emoji.md
- packages/docs/fluent-editor/docs/file-upload.md
- packages/docs/fluent-editor/docs/image-upload.md
- packages/docs/fluent-editor/docs/mention.md
- packages/docs/fluent-editor/docs/table.md
> docs: optimize demos

- .github/workflows/auto-deploy.yml
> ci: auto-deploy add paths

- packages/docs/fluent-editor/docs/mention.md
- packages/fluent-editor/src/mention/Mention.ts
> docs: update MentionOption interface

- packages/docs/fluent-editor/docs/quick-start.md
> docs: optimize quick start docs

- .github/workflows/playwright.yml
- package.json
- packages/docs/package.json
> chore: add install:browser

- packages/docs/fluent-editor/.vitepress/sidebar.ts
- packages/docs/fluent-editor/demos/formula.vue
- packages/docs/fluent-editor/docs/formula.md
- packages/docs/package.json
- pnpm-lock.yaml
> docs: add formula demo

- packages/docs/fluent-editor/.vitepress/sidebar.ts
- packages/docs/fluent-editor/demos/markdown.vue
- packages/docs/fluent-editor/docs/markdown.md
- packages/docs/package.json
- pnpm-lock.yaml
> docs: add markdown demo

- packages/docs/fluent-editor/.vitepress/sidebar.ts
- packages/docs/fluent-editor/demos/get-html.vue
- packages/docs/fluent-editor/docs/formula.md
- packages/docs/fluent-editor/docs/get-html.md
> docs: add get-html demo

- packages/docs/fluent-editor/.vitepress/theme/style.css
- packages/docs/fluent-editor/demos/basic-usage.vue
- packages/docs/fluent-editor/demos/code-block-highlight.vue
- packages/docs/fluent-editor/demos/counter-count.vue
- packages/docs/fluent-editor/demos/counter.vue
- packages/docs/fluent-editor/demos/custom-toolbar.vue
- packages/docs/fluent-editor/demos/emoji.vue
- packages/docs/fluent-editor/demos/file-upload.vue
- packages/docs/fluent-editor/demos/format-painter.vue
- packages/docs/fluent-editor/demos/formula.vue
- packages/docs/fluent-editor/demos/get-html.vue
- packages/docs/fluent-editor/demos/image-upload-to-server.vue
- packages/docs/fluent-editor/demos/image-upload.vue
- packages/docs/fluent-editor/demos/markdown.vue
- packages/docs/fluent-editor/demos/mention-custom-list.vue
- packages/docs/fluent-editor/demos/mention.vue
- packages/docs/fluent-editor/demos/table.vue
- packages/docs/fluent-editor/demos/video.vue
- packages/docs/fluent-editor/docs/quick-start.md
- packages/fluent-editor/package.json
> fix: fix style.scss error

- packages/docs/fluent-editor/demos/table.vue
> docs: optimize table demo

- .all-contributorsrc
- README.zh-CN.md
> docs: update README

- README.md
- README.zh-CN.md
- packages/docs/fluent-editor/.vitepress/sidebar.ts
- packages/docs/fluent-editor/demos/get-content-delta.vue
- packages/docs/fluent-editor/demos/get-content-html.vue
- packages/docs/fluent-editor/demos/set-content-delta.vue
- packages/docs/fluent-editor/demos/set-content-html.vue
- packages/docs/fluent-editor/docs/get-content.md
- packages/docs/fluent-editor/docs/get-html.md
- packages/docs/fluent-editor/docs/set-content.md
- packages/docs/fluent-editor/docs/table.md
- packages/fluent-editor/src/custom-image/image.ts
> docs: add set-content demo

- packages/docs/fluent-editor/.vitepress/config.ts
- packages/docs/fluent-editor/.vitepress/theme/index.ts
- packages/docs/fluent-editor/.vitepress/theme/insert-petercat-assistant.ts
> docs: add petercat assistant

- packages/fluent-editor/package.json
> chore: release v3.25.0

- packages/docs/fluent-editor/.vitepress/components/TranslateComponent.vue
- packages/docs/fluent-editor/.vitepress/config.ts
- packages/docs/fluent-editor/.vitepress/theme/index.ts
- packages/docs/fluent-editor/.vitepress/theme/insert-translate.ts
- packages/docs/fluent-editor/.vitepress/theme/style.css
> docs: add language switch

- packages/docs/fluent-editor/demos/custom-toolbar.vue
- packages/docs/fluent-editor/demos/toolbar-tip.vue
- packages/fluent-editor/src/assets/common.scss
- packages/fluent-editor/src/assets/lineHeight.scss
- packages/fluent-editor/src/assets/toolbar.scss
- packages/fluent-editor/src/attributors/line-height.ts
- packages/fluent-editor/src/config/i18n/en-us.ts
- packages/fluent-editor/src/config/i18n/zh-cn.ts
- packages/fluent-editor/src/config/types/toolbar-item.interface.ts
- packages/fluent-editor/src/fluent-editor.ts
- packages/fluent-editor/src/modules/toolbar/toolbar-tip.ts
- packages/fluent-editor/src/themes/snow.ts
> fix: line-height should be block scope and toolbar change with cursor

- .github/labeler.yml
- packages/docs/fluent-editor/.vitepress/config.ts
- packages/fluent-editor/package.json
> docs: add v3.x entry

- packages/docs/fluent-editor/docs/demo/get-content.md
> docs: rename getContent to getContents

- packages/docs/fluent-editor/demos/formula-mathlive.vue
- packages/fluent-editor/src/config/types/editor-modules.interface.ts
> docs: add set formula content

- .github/labeler.yml
> ci: add issue auto label

- packages/docs/fluent-editor/docs/demo/ai.md
> docs(ai): add warning tip

- packages/docs/fluent-editor/demos/file-upload-handle.vue
- packages/fluent-editor/src/modules/custom-uploader.ts
文件上传 fail 状态插入 \n 会破坏 表格数据结构导致表格展示混乱 ，使用空格占位
表格内插入图片显示正常
> fix(custom-uploader): fail 状态插入 \n 会破坏 表格数据结构 使用空格占位
